name: build

on:
  push:
    branches: [ alexab ]
  pull_request:
    branches: [ alexab ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -j4
